import { Inter } from 'next/font/google'
import './globals.css'
import {Toaster} from "react-hot-toast";
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <body className={inter.className}>
      <Toaster/>
      {children}
      </body>
    </html>
  )
}
